### ISSUE TITLE
Non-Parallel Option

### ISSUE THREAD

**Issue by daxpedda** [samuel-lucas6/draft-lucas-balloon-hashing#19]
https://samuellucas.com/draft-lucas-bkdf/draft-lucas-bkdf.html#section-3-4:
> Note that the internal function calls **MUST** be implemented in parallel, not serially. Otherwise, the `parallelism` parameter essentially becomes another `timeCost` parameter.

It is often desirable to provide a single-threaded implementation as well for platforms without multi-threading support, but this sentence would make this non-standard.

I would propose one of the following:
- Define an error that is returned if `parallelism` is not 1 but the implementation only supports single-threaded.
- Add a separate single-threaded function, e.g. `BKDF_single` (terrible name ... I know).

Unless this was intentional and the idea is that this algorithm should never be used without multi-threading, in which case I would add as much to the specification and also consider disallowing `parallelism` set to 1.

**Comment by samuel-lucas6** [comment]
Thanks for looking at the draft/your feedback.

I debated putting this for that reason. My thinking was an implementation would just support `parallelism` set to 1, like libsodium, in which case that can't be implemented in parallel. However, I think you're right that the wording should be changed to make that clear or this should be removed completely. I was just trying to avoid what happened with scrypt.

Are you happy to be listed in the Acknowledgements section?

**Comment by daxpedda** [comment]
> Are you happy to be listed in the Acknowledgements section?

Sure!
