### ISSUE TITLE
Support for a pepper

### ISSUE THREAD

**Issue by samuel-lucas6** [samuel-lucas6/draft-lucas-balloon-hashing#7]
A secret key could be supported like in [Argon2](https://www.rfc-editor.org/rfc/rfc9106.html#section-3.1). However, I'm not convinced this is a good idea because encrypting password hashes is [preferable](https://github.com/paragonie/password_lock?tab=readme-ov-file#how-is-this-different-than-peppering), as explained in the Security Considerations section. Supporting this would suggest otherwise, even though it could be useful for key derivation.

**Comment by Sc00bz** [comment]
I agree. But you might want to have "extra salts". This is useful for PAKEs where you include the user ID, server ID, OPRF salt (or salt), and local/secret salt (if there is one). This is just to avoid collisions for `H(salt || userId || serverId)` like `H(salt || "user1" || "server")` and `H(salt || "user" || "1server")` etc. It doesn't matter how you do it but the simplest is `salt' = H(H(salt) || H(userId) || H(serverId) || ... )`.

**Comment by samuel-lucas6** [comment]
Could the user not just supply that via the existing salt parameter? They'd obviously have to do proper separation though like encoding the lengths.

**Comment by Sc00bz** [comment]
Yes, but having it as an option prevents the user of the API from needing to think about encoding lengths or other proper separation methods and maybe messing it up. Also it gives a common implemented method for this.

**Comment by samuel-lucas6** [comment]
I hear you. I've not seen any other algorithm do this though. What would the API look like? An array of salts and you append the length of each one?

As mentioned in #14, it will probably be easy to support a pepper once the switch from `Hash()` to `PRF()` is made.

**Comment by Sc00bz** [comment]
C
```
int balloon_kdf(
	void       *output,   size_t outputSize,
	const void *password, size_t passwordSize,
	const void *salt,     size_t saltSize,
	uint32_t    memory, uint32_t iterations, uint32_t parallelism,
	uint32_t    maxThreads, int wipeMem,
	size_t      numExtraSalts = 0, void **extraSalts = NULL, size_t *extraSaltsSizes = NULL);
```
C++
```
int balloon_kdf(
	void *output, size_t outputSize,
	const std:string &password, const std:string &salt,
	uint32_t memory, uint32_t iterations, uint32_t parallelism,
	uint32_t maxThreads, int wipeMem,
	const std:vector<std:string> *extraSalts = NULL);
```
Go
```
func balloon_kdf(
	outputSize int,
	password []byte, salt []byte,
	memory int, iterations int, parallelism int,
	maxThreads int, wipeMem int,
	extraSalts [][]byte) (output []byte, err error) {
...
key, _ := balloon_kdf(
	keySize,
	[]byte("password"), []byte("salt"),
	memory, iterations, parallelism,
	maxThreads, wipeMem,
	nil)
```

**Comment by cipriancraciun** [comment]
Sorry for replying late, but I think having an extra "pepper", in addition to "salt" might be very confusing for the wast majority of non-cryptography-savvy developers.

The developers that do want "peppers" know what they are doing, and they could just fold that into the "salt" (or "associated data").

The current algorithm treats the "pepper" as the initial `key` for the `PRF`, meanwhile the "salt", "personalization" and "associated data" is just concatenated to the "password" as inputs to the said `PRF`.  But this is just by choice.  It could just as well "merged" the salt, pepper, personalization, associated data, into the `key` for the `PRF`.

----

> [...] I agree. But you might want to have "extra salts". [...]

> [...] Yes, but having it as an option prevents the user of the API from needing to think about encoding lengths or other proper separation methods and maybe messing it up.

Then, to make sure the user doesn't just shoot himself in the foot with normalizing multiple salts, peppers, and associated data, (plus personalization), why don't we allow the developer to provide a list of salts.  (Just like in the snippets above, but without the `salt` argument, just keeping the `extraSalts`.)

This way the interface greatly simplifies, and allows the user to choose how many salts, peppers, and associated data to provide.

----

The personalization is perhaps best kept as a separate argument, to make sure that it is hard-coded as a constant to provide application separation.

**Comment by cipriancraciun** [comment]
Also, while reading the RFC draft, I see that the pepper can be at most as long as the `KEY_LEN`, which makes it quite different than the rest of the inputs (password, salt, associated data, personalization, etc.) which can have arbitrary sizes (withit limits).

What should a developer do, when he has a longer pepper than the `KEY_LEN`?  Should he hash it?

Thus, if we want to help the developer in taking the pepper off his hands, we've went just half the way.

----

Also, there is something strange in the way the pepper is canonicalized:
* the pepper contents, padded to `KEY_LEN` is used as the `PRF` key, thus without canonicalization (as a self-contained key);
* but then the pepper length is passed as the `PRF` input, thus applying the pepper canonicalization at this second step;

Although, most likely from a cryptographic point of view it doesn't mater at all (as long as the length is merged somewhere), the implementation seems "strange" or "non-symmetrical".

**Comment by samuel-lucas6** [comment]
> Sorry for replying late, but I think having an extra "pepper", in addition to "salt" might be very confusing for the wast majority of non-cryptography-savvy developers.

I think the draft makes the difference pretty clear, there's a [Wikipedia page](https://en.wikipedia.org/wiki/Pepper_(cryptography)), it's discussed by [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#peppering), and Argon2 supports a pepper, although annoyingly calls it 'secret value'.

The only issue with calling it a pepper is that the word has been used to mean something you rediscover, except I don't think that's caught on compared to it being a secret key. I wish people would just name things properly.

> The developers that do want "peppers" know what they are doing, and they could just fold that into the "salt" (or "associated data").

True, but it's nice separating these things. This makes code clearer, avoids worrying about fixed-length arguments/length encoding, and gives each parameter one purpose. Furthermore, there's a PRF key slot to use and feeding a key into that is theoretically better than feeding a key midway through the message.

> It could just as well "merged" the salt, pepper, personalization, associated data, into the key for the PRF.

Only if you hashed that data; otherwise, the key would have a variable length, which isn't possible with certain functions and also a bad idea with HMAC because it affects it being a dual-PRF. And the issue with hashing is that the algorithm takes a keyed function, so this is basically what's already being done (you'd have to use an empty PRF key).

> Then, to make sure the user doesn't just shoot himself in the foot with normalizing multiple salts, peppers, and associated data, (plus personalization), why don't we allow the developer to provide a list of salts.

a) this doesn't align with existing functions, which will cause confusion, b) this is annoying to implement, and c) barely anybody will use the `associatedData` parameter. I think it complicates rather than simplifies things for little benefit, and there's nothing stopping a particular implementation supporting associated data in a way that encodes the length of each part.

> What should a developer do, when he has a longer pepper than the KEY_LEN? Should he hash it?

They shouldn't use a pepper longer than `KEY_LEN` because that key size is already big enough (128+ bits). Therefore, whilst this could be mentioned, I don't think it's necessary.

> Also, there is something strange in the way the pepper is canonicalized:

This came about after I finally skim read the horrible [dual-PRF paper](https://eprint.iacr.org/2023/861) people were talking about. You need to encode the key length for HMAC/prefix MAC to be a dual-PRF. Doing that next to the key like KMAC doesn't work with certain functions due to key size restrictions, and as you say, this makes no practical difference.
